### ISSUE TITLE
Remove cobble layers

### ISSUE THREAD

**Issue by stefankeidel** [mjaschen/gravel-overlay#3]
I like cobbles just as much as the next person (really do) but I find they detract from the usability of the overlay immensely. Can we either move them to a separate overlay ("Steppenwolf planning") or get rid of them entirely? Didn't want to "just do it" w/o asking 😀 ... so I thought I'd make an issue

**Comment by mjaschen** [comment]
I am (currently) against removing the feature for two reasons:

- I know several people (including myself) who really like it. I think this is a classic YMMV thing.
- Extracting into a separate layer would be possible, but then the question is where to stop (Use a separate layer for cemeteries/water as well? Introduce a separate layer for ways with known bad surfaces?)

**Comment by stefankeidel** [comment]
Alrighty, fair enough. Wouldn't want to take features away from active users
